[phases.setup]
nixpkgsArchive = "23.11"
nixPkgs = ["nodejs_20", "git"]

[phases.install]
cmds = ["npm install"]
dependsOn = ["setup"]

[phases.build]
cmds = ["npm run build"]
dependsOn = ["install"]

[start]
cmd = "npx prisma migrate deploy && node dist/main.js"
